import {Puzzle} from "@/lib/types";

export const puzzles: Puzzle[] = [
  {
    id: "8x8-v1b1-1",
    name: "8x8 #1",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 1, 2, 3, 4, 4, 4], [0, 0, 1, 2, 3, 3, 3, 3], [0, 0, 2, 2, 3, 3, 3, 3], [0, 0, 0, 2, 2, 3, 3, 3], [5, 5, 5, 5, 6, 6, 3, 3], [5, 5, 5, 5, 6, 6, 3, 3], [7, 7, 5, 5, 7, 7, 7, 7], [7, 7, 7, 7, 7, 7, 7, 7]],
    solution: [[false, false, false, false, false, false, true, false], [false, false, true, false, false, false, false, false], [true, false, false, false, false, false, false, false], [false, false, false, false, true, false, false, false], [false, false, false, false, false, false, false, true], [false, false, false, false, false, true, false, false], [false, false, false, true, false, false, false, false], [false, true, false, false, false, false, false, false]],
  },
  {
    id: "8x8-v1b1-2",
    name: "8x8 #2",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 0, 0, 1, 1, 1, 1], [0, 0, 0, 1, 1, 1, 2, 2], [0, 0, 3, 3, 1, 2, 2, 2], [0, 3, 3, 3, 1, 2, 2, 4], [0, 3, 3, 3, 1, 2, 2, 4], [0, 3, 5, 1, 1, 6, 6, 6], [0, 3, 5, 1, 6, 6, 7, 6], [0, 3, 3, 3, 3, 6, 7, 6]],
    solution: [[true, false, false, false, false, false, false, false], [false, false, false, true, false, false, false, false], [false, false, false, false, false, true, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, false, false, false, true], [false, false, true, false, false, false, false, false], [false, false, false, false, true, false, false, false], [false, false, false, false, false, false, true, false]],
  },
  {
    id: "8x8-v1b1-3",
    name: "8x8 #3",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 1, 1, 1, 2, 3, 3], [0, 0, 0, 2, 1, 2, 3, 3], [0, 0, 0, 2, 2, 2, 2, 3], [0, 0, 4, 2, 2, 5, 5, 5], [0, 4, 4, 2, 2, 6, 7, 7], [0, 4, 4, 4, 6, 6, 6, 7], [0, 4, 4, 4, 4, 6, 6, 7], [0, 0, 4, 4, 4, 4, 6, 6]],
    solution: [[false, false, true, false, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, false, true, false, false, false, false], [false, false, false, false, false, true, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, true, false, false, false], [false, false, false, false, false, false, false, true], [true, false, false, false, false, false, false, false]],
  },
  {
    id: "8x8-v1b1-4",
    name: "8x8 #4",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 1, 2, 3, 3, 4, 4], [0, 1, 1, 2, 2, 4, 4, 4], [0, 1, 2, 2, 2, 4, 4, 4], [0, 1, 1, 1, 2, 2, 2, 4], [0, 0, 1, 1, 1, 5, 5, 5], [0, 0, 1, 1, 6, 6, 5, 7], [0, 1, 1, 6, 6, 6, 6, 7], [0, 0, 0, 6, 6, 6, 7, 7]],
    solution: [[false, false, false, false, true, false, false, false], [false, false, false, false, false, false, true, false], [false, false, true, false, false, false, false, false], [true, false, false, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, false, false, false, false, false, true], [false, true, false, false, false, false, false, false], [false, false, false, true, false, false, false, false]],
  },
  {
    id: "8x8-v1b1-5",
    name: "8x8 #5",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 1, 1, 2, 2, 3, 3], [0, 0, 1, 1, 2, 4, 3, 3], [0, 0, 1, 2, 2, 4, 4, 4], [0, 0, 1, 0, 2, 2, 2, 4], [0, 0, 0, 0, 2, 2, 2, 2], [0, 5, 5, 5, 2, 6, 6, 6], [0, 5, 5, 5, 2, 2, 6, 6], [0, 5, 5, 5, 7, 7, 6, 6]],
    solution: [[false, false, true, false, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, false, true, false, false, false, false], [false, false, false, false, false, false, false, true], [true, false, false, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, true, false, false, false]],
  },
  {
    id: "8x8-v1b1-6",
    name: "8x8 #6",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 0, 0, 0, 1, 1, 2], [3, 4, 4, 0, 0, 0, 2, 2], [3, 3, 4, 5, 5, 0, 2, 2], [3, 3, 5, 5, 6, 6, 2, 2], [3, 3, 5, 5, 5, 6, 6, 6], [3, 3, 5, 5, 6, 6, 6, 6], [3, 3, 3, 7, 7, 7, 7, 7], [3, 3, 3, 7, 7, 7, 7, 7]],
    solution: [[false, false, false, false, false, false, true, false], [false, true, false, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, false, false, false, false, false, true], [false, false, true, false, false, false, false, false], [false, false, false, false, true, false, false, false], [true, false, false, false, false, false, false, false], [false, false, false, true, false, false, false, false]],
  },
  {
    id: "8x8-v1b1-7",
    name: "8x8 #7",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 1, 1, 1, 1, 1, 1], [0, 0, 1, 1, 1, 2, 3, 1], [0, 0, 4, 4, 1, 5, 3, 3], [0, 0, 4, 4, 5, 5, 5, 3], [0, 6, 6, 6, 5, 5, 5, 3], [0, 0, 6, 6, 6, 3, 3, 3], [0, 0, 0, 6, 6, 6, 7, 3], [0, 0, 6, 6, 6, 6, 7, 3]],
    solution: [[false, false, false, true, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, true, false, false, false, false, false], [false, false, false, false, true, false, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, false, false, false, true], [true, false, false, false, false, false, false, false], [false, false, false, false, false, false, true, false]],
  },
  {
    id: "8x8-v1b1-8",
    name: "8x8 #8",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 0, 1, 2, 2, 2, 2], [3, 3, 4, 1, 1, 2, 2, 2], [3, 3, 4, 4, 4, 5, 2, 2], [3, 4, 4, 4, 4, 5, 6, 5], [7, 4, 4, 4, 4, 5, 6, 5], [7, 7, 7, 7, 4, 5, 5, 5], [7, 7, 7, 7, 5, 5, 5, 5], [7, 7, 7, 7, 5, 5, 5, 5]],
    solution: [[false, true, false, false, false, false, false, false], [false, false, false, true, false, false, false, false], [false, false, false, false, false, false, false, true], [true, false, false, false, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, false, false, true, false, false, false], [false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false]],
  },
  {
    id: "8x8-v1b1-9",
    name: "8x8 #9",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 1, 1, 1], [0, 0, 0, 2, 3, 3, 1, 1], [4, 0, 2, 2, 4, 4, 4, 1], [4, 4, 4, 4, 4, 4, 4, 1], [5, 5, 5, 4, 4, 4, 4, 1], [6, 5, 5, 4, 1, 1, 1, 1], [6, 7, 7, 7, 7, 1, 1, 1]],
    solution: [[false, true, false, false, false, false, false, false], [false, false, false, false, false, false, false, true], [false, false, false, false, false, true, false, false], [false, false, false, true, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, true, false, false, false, false, false], [true, false, false, false, false, false, false, false], [false, false, false, false, true, false, false, false]],
  },
  {
    id: "8x8-v1b1-10",
    name: "8x8 #10",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 0, 1, 2, 2, 1, 3], [0, 0, 0, 1, 1, 1, 1, 3], [0, 0, 0, 1, 1, 4, 3, 3], [0, 0, 1, 1, 4, 4, 3, 3], [0, 0, 1, 1, 4, 3, 3, 3], [5, 5, 1, 1, 4, 3, 3, 3], [6, 1, 1, 7, 4, 4, 3, 3], [6, 7, 7, 7, 4, 4, 3, 3]],
    solution: [[false, false, false, false, true, false, false, false], [false, false, false, false, false, false, true, false], [false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, false, false, false, false, false, true], [false, true, false, false, false, false, false, false], [false, false, false, true, false, false, false, false], [true, false, false, false, false, false, false, false]],
  },
  {
    id: "8x8-v1b1-11",
    name: "8x8 #11",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 0, 0, 1, 2, 2, 2], [0, 0, 0, 0, 1, 2, 2, 2], [0, 3, 3, 0, 1, 4, 2, 2], [1, 1, 1, 1, 1, 4, 1, 2], [1, 1, 5, 5, 1, 1, 1, 2], [6, 5, 5, 5, 5, 5, 5, 2], [6, 5, 5, 7, 7, 5, 2, 2], [6, 5, 5, 5, 5, 5, 2, 2]],
    solution: [[false, false, false, true, false, false, false, false], [false, false, false, false, false, false, false, true], [false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, false, false, true, false, false, false], [true, false, false, false, false, false, false, false]],
  },
  {
    id: "8x8-v1b1-12",
    name: "8x8 #12",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 0, 1, 1, 1, 2, 2], [0, 0, 1, 1, 1, 3, 3, 2], [0, 0, 4, 1, 1, 3, 3, 2], [0, 5, 5, 5, 1, 3, 3, 2], [6, 6, 6, 5, 3, 3, 2, 2], [6, 6, 6, 6, 3, 3, 3, 3], [7, 7, 7, 7, 7, 7, 7, 3], [7, 7, 7, 7, 7, 7, 7, 7]],
    solution: [[false, false, false, false, false, false, true, false], [false, false, false, false, true, false, false, false], [false, false, true, false, false, false, false, false], [true, false, false, false, false, false, false, false], [false, false, false, true, false, false, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, false, false, false, true], [false, false, false, false, false, true, false, false]],
  },
  {
    id: "8x8-v1b1-13",
    name: "8x8 #13",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 1, 1, 1, 1, 1, 2], [3, 0, 0, 2, 2, 2, 2, 2], [3, 3, 0, 0, 0, 2, 2, 4], [3, 3, 0, 0, 5, 5, 5, 4], [3, 3, 0, 0, 5, 5, 5, 4], [3, 3, 3, 3, 6, 5, 5, 7], [3, 3, 3, 6, 6, 6, 7, 7], [3, 3, 6, 6, 6, 6, 7, 7]],
    solution: [[false, false, false, true, false, false, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, false, false, false, false, false, true], [false, false, false, false, true, false, false, false], [true, false, false, false, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, true, false, false, false, false, false]],
  },
  {
    id: "8x8-v1b1-14",
    name: "8x8 #14",
    size: 8,
    difficulty: "easy",
    regions: [[0, 1, 2, 2, 3, 3, 3, 4], [0, 1, 1, 2, 2, 3, 3, 4], [0, 0, 1, 1, 1, 1, 3, 4], [0, 0, 1, 1, 5, 5, 4, 4], [0, 1, 1, 1, 1, 5, 4, 4], [0, 0, 0, 1, 5, 5, 4, 4], [0, 0, 0, 6, 6, 6, 6, 6], [0, 0, 0, 6, 6, 6, 6, 7]],
    solution: [[false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false], [true, false, false, false, false, false, false, false], [false, false, false, false, true, false, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, false, true, false, false, false, false], [false, false, false, false, false, false, false, true]],
  },
  {
    id: "8x8-v1b1-15",
    name: "8x8 #15",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 1, 0, 0, 0, 0], [1, 1, 1, 2, 2, 2, 3, 0], [1, 1, 3, 3, 3, 3, 3, 3], [1, 1, 4, 4, 3, 3, 3, 3], [1, 1, 4, 5, 6, 6, 6, 6], [1, 1, 4, 5, 5, 6, 6, 6], [7, 1, 1, 5, 5, 5, 5, 6]],
    solution: [[false, true, false, false, false, false, false, false], [false, false, false, true, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, false, false, false, false, false, true], [false, false, true, false, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, false, false, true, false, false, false], [true, false, false, false, false, false, false, false]],
  },
  {
    id: "8x8-v1b1-16",
    name: "8x8 #16",
    size: 8,
    difficulty: "easy",
    regions: [[0, 1, 1, 1, 1, 1, 2, 2], [1, 1, 2, 2, 2, 2, 2, 2], [1, 1, 1, 2, 2, 2, 2, 2], [1, 1, 1, 3, 3, 3, 3, 2], [4, 4, 5, 5, 5, 3, 3, 3], [4, 4, 5, 5, 5, 3, 3, 3], [4, 4, 5, 6, 3, 3, 3, 3], [4, 4, 5, 6, 3, 3, 7, 7]],
    solution: [[true, false, false, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, true, false, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, false, false, true, false, false, false], [false, true, false, false, false, false, false, false], [false, false, false, true, false, false, false, false], [false, false, false, false, false, false, false, true]],
  },
  {
    id: "8x8-v1b1-17",
    name: "8x8 #17",
    size: 8,
    difficulty: "easy",
    regions: [[0, 1, 1, 1, 1, 2, 2, 2], [0, 0, 0, 3, 3, 2, 2, 2], [0, 0, 4, 4, 4, 4, 2, 2], [5, 5, 4, 4, 4, 2, 2, 2], [5, 5, 5, 6, 4, 7, 7, 7], [5, 5, 5, 6, 6, 7, 7, 6], [5, 5, 5, 5, 6, 6, 6, 6], [5, 5, 5, 6, 6, 6, 6, 6]],
    solution: [[false, true, false, false, false, false, false, false], [false, false, false, true, false, false, false, false], [true, false, false, false, false, false, false, false], [false, false, false, false, false, false, false, true], [false, false, false, false, true, false, false, false], [false, false, false, false, false, false, true, false], [false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false]],
  },
  {
    id: "8x8-v1b1-18",
    name: "8x8 #18",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 0, 0, 1, 1, 2, 2], [3, 3, 0, 0, 0, 0, 2, 2], [3, 0, 0, 4, 4, 4, 2, 2], [3, 0, 0, 4, 4, 2, 2, 2], [3, 4, 4, 4, 4, 2, 2, 2], [3, 3, 4, 4, 4, 4, 2, 5], [6, 3, 7, 7, 7, 4, 2, 5], [6, 3, 3, 3, 3, 3, 2, 2]],
    solution: [[false, false, false, false, false, true, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, true, false, false, false, false, false], [false, false, false, false, true, false, false, false], [false, false, false, false, false, false, false, true], [false, false, false, true, false, false, false, false], [true, false, false, false, false, false, false, false]],
  },
  {
    id: "8x8-v1b1-19",
    name: "8x8 #19",
    size: 8,
    difficulty: "easy",
    regions: [[0, 1, 1, 1, 2, 2, 2, 2], [0, 1, 1, 1, 1, 1, 2, 2], [3, 1, 1, 4, 5, 1, 2, 2], [3, 1, 1, 4, 5, 5, 5, 2], [3, 3, 6, 6, 5, 5, 2, 2], [3, 3, 3, 6, 5, 5, 2, 2], [3, 3, 3, 5, 5, 5, 7, 7], [3, 3, 3, 3, 5, 5, 5, 5]],
    solution: [[true, false, false, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, false, true, false, false, false, false], [false, false, false, false, false, false, false, true], [false, false, true, false, false, false, false, false], [false, false, false, false, true, false, false, false], [false, false, false, false, false, false, true, false], [false, true, false, false, false, false, false, false]],
  },
  {
    id: "8x8-v1b1-20",
    name: "8x8 #20",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 0, 1, 1, 2, 2, 2], [0, 0, 1, 1, 2, 2, 3, 2], [0, 0, 0, 2, 2, 2, 3, 3], [0, 4, 4, 4, 3, 3, 3, 3], [0, 0, 4, 4, 4, 3, 3, 3], [0, 4, 4, 4, 5, 3, 3, 6], [0, 0, 4, 5, 5, 5, 6, 6], [0, 0, 4, 4, 5, 7, 7, 7]],
    solution: [[true, false, false, false, false, false, false, false], [false, false, true, false, false, false, false, false], [false, false, false, false, true, false, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, false, false, false, false, false, true], [false, false, false, true, false, false, false, false], [false, false, false, false, false, false, true, false]],
  },
  {
    id: "8x8-v1b1-21",
    name: "8x8 #21",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 1, 2, 3, 4, 4, 4], [0, 0, 1, 2, 3, 3, 2, 4], [1, 1, 1, 2, 2, 2, 2, 4], [1, 5, 5, 6, 2, 2, 2, 4], [7, 5, 5, 6, 2, 4, 4, 4], [7, 5, 5, 5, 2, 4, 4, 4], [5, 5, 5, 2, 2, 2, 4, 4], [5, 5, 5, 5, 5, 2, 4, 4]],
    solution: [[false, true, false, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, true, false, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, false, true, false, false, false, false], [true, false, false, false, false, false, false, false], [false, false, false, false, false, false, false, true], [false, false, false, false, true, false, false, false]],
  },
  {
    id: "8x8-v1b1-22",
    name: "8x8 #22",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 0, 1, 2, 2, 3, 3], [4, 0, 2, 2, 2, 3, 3, 3], [4, 0, 0, 0, 2, 2, 2, 5], [4, 0, 0, 0, 0, 6, 5, 5], [4, 0, 4, 4, 4, 6, 5, 5], [4, 4, 4, 7, 4, 7, 5, 5], [4, 4, 4, 7, 7, 7, 7, 7], [4, 4, 7, 7, 7, 7, 7, 7]],
    solution: [[false, false, false, true, false, false, false, false], [false, false, false, false, false, false, true, false], [false, false, false, false, true, false, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, false, false, false, false, false, true], [true, false, false, false, false, false, false, false], [false, false, true, false, false, false, false, false]],
  },
  {
    id: "8x8-v1b1-23",
    name: "8x8 #23",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 1, 1, 1, 2, 3, 3], [0, 0, 1, 1, 2, 2, 3, 3], [0, 0, 1, 2, 2, 3, 3, 4], [0, 0, 1, 1, 2, 3, 3, 4], [0, 0, 1, 1, 2, 5, 5, 4], [0, 0, 0, 1, 5, 5, 4, 4], [0, 6, 6, 5, 5, 5, 4, 7], [0, 0, 6, 5, 5, 5, 7, 7]],
    solution: [[false, false, true, false, false, false, false, false], [true, false, false, false, false, false, false, false], [false, false, false, true, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, false, false, false, false, false, true], [false, false, false, false, true, false, false, false], [false, true, false, false, false, false, false, false], [false, false, false, false, false, false, true, false]],
  },
  {
    id: "8x8-v1b1-24",
    name: "8x8 #24",
    size: 8,
    difficulty: "easy",
    regions: [[0, 0, 1, 1, 1, 1, 1, 1], [0, 0, 0, 1, 1, 1, 1, 1], [0, 0, 0, 1, 1, 2, 1, 1], [0, 0, 0, 2, 2, 2, 3, 3], [4, 0, 0, 2, 2, 5, 5, 3], [4, 6, 0, 0, 7, 5, 5, 5], [6, 6, 7, 0, 7, 7, 5, 5], [6, 6, 7, 7, 7, 5, 5, 5]],
    solution: [[false, false, false, false, true, false, false, false], [false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false], [false, false, false, false, false, false, false, true], [true, false, false, false, false, false, false, false], [false, false, false, false, false, false, true, false], [false, true, false, false, false, false, false, false], [false, false, false, true, false, false, false, false]],
  },
];
